### ISSUE TITLE
Doesn't indent javascript in tag files

### ISSUE THREAD

**Issue by gelus** [ryym/vim-riot#1]
When in a .tag file the indentation does not get applied inside <script> tags or <style type=*> tags.

It seems this is because there is a missing `GetJavascriptIndent()` Method refered to in indent.vim

for now I've changed it to return just the same indentation.
Thanks!

**Comment by ryym** [comment]
Probably you don't install [vim-javascript](https://github.com/pangloss/vim-javascript)?
`GetJavascriptIndent()` is defined in that plugin and this plugin depends on it so you have to install it too ([README](https://github.com/ryym/vim-riot#vim-riot)).

But, I found the indentation doesn't work correctly with the latest version of vim-javascript :sweat:.
I confirmed vim-riot works fine with vim-javascript before pangloss/vim-javascript@32e7c787.
Thanks for the report.

**Comment by gelus** [comment]
Ah, That would be it then. I saw pathogen and just went for it. Glad some good came from my neglecting to read things. We'll pretend that is what I meant.

**Comment by ryym** [comment]
Yeah, then let's keep this issue open :)
I'll investigate this problem later!
