### ISSUE TITLE
Syntax highlighting turns off when class is added to parent tag

### ISSUE THREAD

**Issue by micburks** [ryym/vim-riot#3]
First of all, thanks for the plugin!

When writing a custom tags, e.g.:
```
<MyTag>
  /* definition */
</MyTag>
```

Often I use them to implement a number of classes like this:
```
<MyTag class='u-reset List List--inline'>
  /* definition */
</MyTag>
```

But syntax highlighting doesn't support classes (or any attributes) on the parent tag. As far as I can tell, RiotJS is indifferent about using custom tags this way. I imagine this isn't too difficult to fix, but I haven't yet looked into making the fix myself.

**Comment by ryym** [comment]
Thank you for the report!
I fixed the problem and updated the master branch.
Could you update your local `vim-riot` and confirm that it is fixed?

**Comment by micburks** [comment]
Looks great! Thanks for the quick fix!
